# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

target 'aic' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aic
  pod 'PureLayout'
  pod 'SWXMLHash', '~> 5.0.0'
  pod 'Alamofire', '~> 4.9.0'
  pod 'Kingfisher', '~> 5.11.0'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Localize-Swift', '~> 3.1.0'
  pod "Atributika"
  pod 'Firebase/Analytics'

  target 'aicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
