# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'aic' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aic
  pod 'Google/Analytics'
  pod 'PureLayout'
  pod 'Kingfisher', '~> 4.0'

  target 'aicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
