# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'aic' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aic
  pod 'Firebase/Core'
  pod 'PureLayout'
  pod 'SWXMLHash', '~> 4.2.1'
  pod 'Alamofire', '~> 4.5.1'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'Localize-Swift', '~> 2.0'
  pod "Atributika"
  pod 'Fabric'
  pod 'Answers'

  target 'aicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'aicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
